version: '3.8'
services:
  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

volumes:
  mongo_data:
